# Application Name & Port
spring.application.name=learnhub
server.port=${PORT:8080}

# Supabase PostgreSQL Configuration
# Note: Replace <project-ref> and <password> with actual Supabase details
# Example: jdbc:postgresql://db.<project-ref>.supabase.co:5432/postgres

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.yknnwbgnrhbbxngfzxej
spring.datasource.password=7P5dnEoIusj7FgDp
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP connection pool (VERY IMPORTANT for Supabase)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000



# JPA Config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


